# 一、nadarray
## ndarray的特性
### 多维性

In [1]:
import numpy as np

In [5]:
arr = np.array(5) # 创建0维的数组
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

5
0
()
int64


In [6]:
arr = np.array([1,2,3]) # 创建0维的数组
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

[1 2 3]
1
(3,)
int64


In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) # 创建0维的数组
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr.flags)
arr = arr.T
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)
12
int64
8
96
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
2
(3, 4)
12
int64


## 同质性