In [2]:
from statistics import mean

import numpy as np
from numpy import dtype

arr = np.zeros((3,4), dtype=int)
print(arr)
print(arr.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(3, 4)


In [4]:
arr = np.zeros((3,), dtype=int)
print(arr)
print(arr.shape)

[0 0 0]
(3,)


In [11]:
arr = np.empty((3,4))
print(arr)
print(arr.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)


In [12]:
arr = np.full((3,4),2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [13]:
arr1 = np.zeros_like(arr)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [16]:
arr = np.arange(2,10,2)
print(arr)

[2 4 6 8]


In [21]:
arr = np.linspace(0,100,5,dtype=int)
print(arr)

[  0  25  50  75 100]


In [23]:
arr = np.logspace(0,4,2,base=2)
print(arr)
arr = np.logspace(0,4,3,base=2)
print(arr)

[ 1. 16.]
[ 1.  4. 16.]


In [4]:
# 单位矩阵
arr = np.eye(3,4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [7]:
# 对角矩阵
arr = np.diag([3,4])
print(arr)

[[3 0]
 [0 4]]


In [8]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2,3)
print(arr)

[[0.37624666 0.37076684 0.68219995]
 [0.75349684 0.18524534 0.29014051]]


In [9]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(low=3,high=6,size=(2,3))
print(arr)

[[4.28727301 3.7520046  5.03624494]
 [5.4445293  5.64036553 4.03301178]]


In [24]:
# 生成指定范围区间的随机整数
arr = np.random.randint(low=3,high=6,size=(2,3))
print(arr)

[[5 5 4]
 [5 4 4]]


In [25]:
# 生成随机数列（正态分布）
arr = np.random.randn(2,3)
print(arr)

[[ 1.17868961 -0.59674828  0.29958582]
 [ 0.82111601 -0.06174807  0.19952686]]


In [27]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1,10,size=(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


In [33]:
arr = np.array([1,0,0,2],dtype=np.bool)
print(arr)

[ True False False  True]


In [36]:
arr = np.array([1,0,0,2000],dtype=int)
print(arr)

[   1    0    0 2000]


In [37]:
arr = np.array([1,0,0,2],dtype=np.float64)
print(arr)

[1. 0. 0. 2.]


In [44]:
# 一维数组的索引与切片
arr = np.random.randint(1,100,20)
print(arr)

[41 12 70  1 59 87 38 69 19 10 58 15 36 76 24 30 61 98  3 20]


In [49]:
print(arr[0])
print(arr[2:15])
print(arr[(arr>10) & (arr<70)])
print(arr[slice(2,15,2)])

41
[70  1 59 87 38 69 19 10 58 15 36 76 24]
[41 12 59 38 69 19 58 15 36 24 30 61 20]
[70 59 38 19 58 36 24]


In [50]:
# 二维数组的索引与切片
arr = np.random.randint(1,100,(4,8))
print(arr)

[[87 46 86 85 85 61 46 25]
 [76 56 66 83 52 13 37 42]
 [75 97 96 86 32 68 77 43]
 [ 3 40 97 87 80  8 12 86]]


In [60]:
print(arr[1,3])
print(arr[1:3,2:5])
print(arr[2,:][arr[2]>70])
print(arr[:,3][arr[:,3]>70][slice(0,3,2)])

83
[[66 83 52]
 [96 86 32]]
[75 97 96 86 77]
[85 86]


In [63]:
# 算术运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [64]:
# 算术运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[9,10,11]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[[ 5  7  9]
 [11 13 15]
 [16 18 20]]
[[-3 -3 -3]
 [-3 -3 -3]
 [-2 -2 -2]]
[[ 4 10 18]
 [28 40 54]
 [63 80 99]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [0.77777778 0.8        0.81818182]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [66]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a + 3)
print(a - 3)
print(a * 3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [68]:
# 广播机制：1、获取形状.2、是否广播
# 同一维度：相同、1
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)

[1 2 3]
[[4]
 [5]
 [6]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[-3 -2 -1]
 [-4 -3 -2]
 [-5 -4 -3]]
[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


In [69]:
a = np.array([1,2,3])
b = np.array([[4]])
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)

[1 2 3]
[[4]]
[[5 6 7]]
[[-3 -2 -1]]
[[ 4  8 12]]


In [70]:
# 矩阵运算
a = np.array([[1,2,3],[4,5,6],[6,7,8]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a @ b)
print(b @ a)

[[ 21  27  33]
 [ 57  72  87]
 [ 81 102 123]]
[[ 60  75  90]
 [ 93 117 141]
 [ 27  33  39]]


In [72]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [77]:
# 计算指数 e^x
print(np.exp(1))
# 计算自然对数 lnX
print(np.log(2.71))
arr = np.exp(2)
print(np.log(arr))

2.718281828459045
0.9969486348916096
2.0


In [80]:
# 计算正弦值、余弦值
print(np.sin(30))
print(np.cos(np.pi))

-0.9880316240928618
-1.0


In [81]:
# 计算绝对值
arr = np.array([1,-1,-2])
print(np.abs(arr))

[1 1 2]


In [83]:
# 计算a的b次幂
print(np.power(arr,3))

[ 1 -1 -8]


In [87]:
# 四舍五入
print(np.round([3.2,4.5,4.51,8.1,9.6]).astype(int))

[ 3  4  5  8 10]


In [89]:
# 向上取整，向下取整
arr = np.array([3.2,4.5,4.51,8.1,9.6])
print(np.ceil(arr))
print(np.floor(arr))

[ 4.  5.  5.  9. 10.]
[3. 4. 4. 8. 9.]


In [91]:
# 检测缺失值 NaN
np.isnan([1,2,np.nan,3])


array([False, False,  True, False])

In [92]:
arr = np.random.randint(1,20,8)
print(arr)

[ 8  6  2  7 13  5  7  1]


In [3]:
# 求和
print(np.sum(arr))
print(arr)
# 计算平均值
print(np.mean(arr))
# 计算中位数
print(np.median(arr))
# 计算标准差
print(np.std(arr))
# 计算方差
print(np.var(arr))
# 计算最小值 返回最小值索引
print(np.min(arr),np.argmin(arr))
# 计算最大值 返回最大值索引
print(np.max(arr),np.argmax(arr))
# 计算分位数
print(np.percentile(arr,25))
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
# 计算累计和
print(np.cumsum(arr))
# 计算累计积
print(np.cumprod(arr))

0
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
0.0
0.0
0.0
0.0
0 0
0 0
0.0
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  6 10 15 21 28 36 45 55]
[      1       2       6      24     120     720    5040   40320  362880
 3628800]


In [6]:
# 是否大于
print(np.greater([1,2,3,4,5,6,7,8,9,10],4))
# 是否小于
print(np.less([1,2,3,4,5,6,7,8,9,10],4))
# 是否等于
print(np.equal([1,2,3,4,5,6,7,8,9,10],4))
# 是否不等于
print(np.not_equal([1,2,3,4,5,6,7,8,9,10],4))
# 是否大于等于
print(np.greater_equal([1,2,3,4,5,6,7,8,9,10],4))
# 是否小于等于
print(np.less_equal([1,2,3,4,5,6,7,8,9,10],4))
# 是否在范围内
print(np.logical_and([1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]))
print(np.logical_or([1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]))
print(np.logical_not([1,2,3,4,5,6,7,8,9,10]))

[False False False False  True  True  True  True  True  True]
[ True  True  True False False False False False False False]
[False False False  True False False False False False False]
[ True  True  True False  True  True  True  True  True  True]
[False False False  True  True  True  True  True  True  True]
[ True  True  True  True False False False False False False]


In [8]:
# 检查元素是否至少有一个元素为True
print(np.any([1,2,3,4,5,6,7,8,9,10]))
# 检查元素是否全部为True
print(np.all([1,2,3,4,5,6,7,8,9,10]))
# 自定义条件
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.where(arr>5,arr,0))

True
True
[ 0  0  0  0  0  6  7  8  9 10]


In [10]:
score = np.random.randint(50,100,20)
print(score)
print(np.where(score>80,'优秀','不及格'))

[71 62 68 91 66 90 99 60 97 67 75 76 89 81 51 65 50 69 69 59]
['不及格' '不及格' '不及格' '优秀' '不及格' '优秀' '优秀' '不及格' '优秀' '不及格' '不及格' '不及格' '优秀'
 '优秀' '不及格' '不及格' '不及格' '不及格' '不及格' '不及格']


In [11]:
print(np.where(score<60,'不及格',np.where(score<80,'良好','优秀')))

['及格' '及格' '及格' '优秀' '及格' '优秀' '优秀' '及格' '优秀' '及格' '及格' '及格' '优秀' '优秀'
 '不及格' '及格' '不及格' '及格' '及格' '不及格']


In [15]:
# np.select(条件,返回的结果)
print(np.select([score<60,(score>=60)&(score<80),score<100],['不及格','良好','优秀'],default='未知'))

['良好' '良好' '良好' '优秀' '良好' '优秀' '优秀' '良好' '优秀' '良好' '良好' '良好' '优秀' '优秀'
 '不及格' '良好' '不及格' '良好' '良好' '不及格']


In [18]:
# 排序
arr = np.random.randint(1,100,20)
print(np.sort(arr))
print(np.argsort(arr))

[ 3  7  9 18 25 28 36 37 41 48 51 51 59 62 67 74 77 93 96 99]
[ 6 13 15 14  1 11 17  8 16 18  0  2  5  9  7  3 12  4 19 10]


In [22]:
# 排序
arr = np.array([[100,2,3],[4,5,6],[7,8,9]])
print(np.sort(arr))

[[  2   3 100]
 [  4   5   6]
 [  7   8   9]]


In [27]:
# 排序
arr = np.array([[7,5,9],[1,8,3],[4,2,6]])
print(arr)
print(np.sort(arr,axis=0)) # 按列排序
print(np.sort(arr,axis=1)) # 按行排序

[[7 5 9]
 [1 8 3]
 [4 2 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 7 9]
 [1 3 8]
 [2 4 6]]


In [25]:
# 去重函数
arr = np.random.randint(1,100,20)
print(arr)
print(np.unique(arr))

[30 75 89  2 72  6 10 70 42 42 96 56 17 19 87 49 38 90 79  3]
[ 2  3  6 10 17 19 30 38 42 49 56 70 72 75 79 87 89 90 96]


In [31]:
# 合并函数
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)
print(np.concatenate([arr1,arr2]))
print(np.vstack([arr1,arr2]))
print(np.hstack([arr1,arr2]))

[5 7 9]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [40]:
# 分割函数
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(np.split(arr,2))
print(np.split(arr,[2,4,6]))

[ 1  2  3  4  5  6  7  8  9 10]
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([ 7,  8,  9, 10])]


In [39]:
# 调整数组的形状
arr = np.random.randint(1,100,10)
print(arr)
print(np.reshape(arr,[5,2]))

[26 97 26 60 21 29 66  2 94 40]
[[26 97]
 [26 60]
 [21 29]
 [66  2]
 [94 40]]


In [ ]:
"""
题目 1: 温度数据分析
某城市一周的最高气温(℃)为 [28, 30, 29, 31, 32, 30, 29]。
- 计算平均气温、最高气温和最低气温
- 找出气温超过 30℃ 的天数
"""

In [43]:
arr = np.array([28, 30, 29, 31, 32, 30, 29])
avg = np.mean(arr)
max = np.max(arr)
min = np.min(arr)
print(f"平均气温: {avg:.2f}℃, 最高气温: {max}℃, 最低气温: {min}℃")
print(f"气温超过 30℃ 的天数: {np.sum(arr>30)}天")
print(np.where(arr>30,arr,0))

平均气温: 29.86℃, 最高气温: 32℃, 最低气温: 28℃
气温超过 30℃ 的天数: 2天
[ 0  0  0 31 32  0  0]


In [ ]:
"""
题目 2：学生成绩统计
某班级 5 名学生的数学成绩为 [85, 90, 78, 92, 88]。
- 计算成绩的平均分、中位数和标准差。
- 将成绩转换为（假设满分为 10）。
"""

In [7]:
arr = np.array([85, 90, 78, 92, 88])
print(f"平均分：",np.mean(arr))
print(f"中位数：",np.median(arr))
print(f"标准差：%.3f"% np.std(arr))
print(arr/10)


平均分： 86.6
中位数： 88.0
标准差：4.883
[8.5 9.  7.8 9.2 8.8]


In [ ]:
"""
题目 3: 矩阵运算
给定矩阵 A = [[1, 2], [3, 4]] 和 B = [[5, 6], [7, 8]]。
- 计算 A + B 和 A * B（逐元素乘法）。
- 计算 A 和 B 的矩阵乘法（点积）。
"""

In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a + b)
print(a * b)
print(a @ b)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
"""
题目 4：随机数据生成
生成一个（3, 4）的随机整数数组，范围 [0, 10)。
- 计算每列的最大值和每行的最小值。
- 将数组中的所有奇数替换为 -1。
"""

In [16]:
arr = np.random.randint(0,10,[3,4])
print(arr)
print('每列的最大值',np.max(arr,axis=0))
print('每行的最小值',np.min(arr,axis=1))
print(np.where(arr%2==1,-1,arr))

[[9 9 3 9]
 [6 9 3 9]
 [0 3 6 5]]
每列的最大值 [9 9 6 9]
每行的最小值 [3 3 0]
[[-1 -1 -1 -1]
 [ 6 -1 -1 -1]
 [ 0 -1  6 -1]]


In [ ]:
"""
题目 5：数组变形
创建一个 1 到 12 的一维数组，并转换为（3, 4）的二维数组
- 计算每行的和与每列的平均值。
- 将数组展平为一维数组。
"""

In [25]:
arr = np.arange(1,13)
print(arr)
arr = np.reshape(arr,[3,4])
print(arr)
print('每行的和：',np.sum(arr,axis=1))
print('每列的平均值',np.mean(arr,axis=0).astype(int))
print(np.reshape(arr,[12]))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和： [10 26 42]
每列的平均值 [5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
"""
生成一个（5, 5）的随机数组，范围 [0, 20)。
- 找出数组中大于 10 的元素。
- 将所有大于 10 的元素替换为 0。
"""

In [31]:
arr = np.random.randint(0,20,[5,5])
print(arr)
print('数组中大于10的元素：',arr[arr>10])
print('将所有大于10的元素替换为0：',np.where(arr>10,0,arr))

[[17 15  3 14 13]
 [18 16  3  0 15]
 [19 16  9 11  4]
 [ 4 11  8  3  5]
 [18 17  6  3  9]]
数组中大于10的元素： [17 15 14 13 18 16 15 19 16 11 11 18 17]
将所有大于10的元素替换为0： [[0 0 3 0 0]
 [0 0 3 0 0]
 [0 0 9 0 4]
 [4 0 8 3 5]
 [0 0 6 3 9]]


In [ ]:
"""
题目 7：统计函数应用
某公司 6 个月的销售额（万元）为 [120, 135, 110, 125, 130, 140]。
- 计算销售额的总和、均值和方差。
- 找出销售额最高的月份和最低的月份。
"""

In [36]:
sale = np.array([120, 135, 110, 125, 130, 140])
print('销售额总和：',np.sum(sale))
print('销售额均值：%.2f'% np.mean(sale))
print('销售额方差：%.2f'% np.var(sale))
print('销售额最高月份：',np.argmax(sale)+1)
print('销售额最低月份：',np.argmin(sale)+1)

销售额总和： 760
销售额均值：126.67
销售额方差：97.22
销售额最高月份： 6
销售额最低月份： 3


In [ ]:
"""
题目 8：数组拼接
给定 A = [1, 2, 3] 和 B = [4, 5, 6]。
- 将 A 和 B 水平拼接为一个新数组。
- 将 A 和 B 垂直拼接为一个新数组。
"""

In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('水平拼接：',np.hstack((a,b)))
print('垂直拼接：',np.vstack((a,b)))

水平拼接： [1 2 3 4 5 6]
垂直拼接： [[1 2 3]
 [4 5 6]]


In [ ]:
"""
题目 9：唯一值与排序
给定数组 [2, 1, 2, 3, 1, 4, 3]。
- 找出数组中的唯一值并排序。
- 计算每个唯一值出现的次数。
"""

In [43]:
arr = np.array([2, 1, 2, 3, 1, 4, 3])
unique_values,counts = np.unique(arr,return_counts=True)
print(unique_values)
print(counts)

[1 2 3 4]
[2 2 2 1]


In [ ]:
"""
题目 20：综合应用
某商店 5 天的销售额（万元）和成本（万元）如下：
销售额：[20, 25, 22, 30, 28]
成本：[15, 18, 16, 22, 20]
- 计算每天的利润（销售额 - 成本）。
- 计算利润的平均值和标准差。
- 找出利润最高的天数。
"""

In [52]:
sale = np.array([20, 25, 22, 30, 28])
cost = np.array([15, 18, 16, 22, 20])
profit = sale - cost
print(profit)
print(np.mean(profit))
print(np.std(profit))
print(profit[profit==np.max(profit)])
print(len(profit[profit==np.max(profit)]))

[5 7 6 8 8]
6.8
1.16619037896906
[8 8]
2
